-- =========================================================
-- MIGRASI — jalankan SEKALI SAJA kalau database SIKasapa Anda
-- sudah pernah di-deploy SEBELUM fitur "Hari Libur Ekstra" ada
-- (kalau baru mulai dari nol, tidak perlu file ini — cukup
-- schema.sql, yang sudah menyertakan kolom ini).
--
-- Jalankan lewat:
--   npx wrangler d1 execute sikasapa-db --remote --file=./migrasi-hari-libur.sql
--
-- Aman dijalankan terhadap data yang sudah ada (tidak menghapus
-- apa pun) — cuma menambah SATU kolom baru dengan nilai default
-- '[]' (array kosong) untuk baris pengaturan yang sudah ada.
-- Kalau kolom ini SUDAH ada (mis. sudah pernah dijalankan
-- sebelumnya, atau database dibuat dari schema.sql versi baru),
-- perintah ini akan gagal dengan pesan "duplicate column name" —
-- itu artinya migrasi ini memang tidak perlu dijalankan lagi.
-- =========================================================
ALTER TABLE pengaturan ADD COLUMN hari_libur TEXT DEFAULT '[]';
